### ISSUE TITLE
Implementar layout

### ISSUE THREAD

**Issue by rafaeleyng** [CWISoftware/drops#3]
Implementar o HTML + CSS básico do layout criado pelo Fabiano Daudt

Lista de drops:
![1-listadrops](https://cloud.githubusercontent.com/assets/4842605/11850509/e3f2ac1e-a414-11e5-8bcb-b5e685c03bd4.png)

Drop:
![2-detalhe-drops](https://cloud.githubusercontent.com/assets/4842605/11850510/e3f7e18e-a414-11e5-9b89-6eb837e7e08f.png)

Menu aberto:
![3-menuaberto](https://cloud.githubusercontent.com/assets/4842605/11850511/e3fcd054-a414-11e5-9c42-81e895ee6f87.png)

**Comment by brunotrassante** [comment]
Caras aproveitando para fazer uns comentários. Aquele cabeçalho que está nesse layput, recentemente gente combinou com o marketing de parar de usar aquele header poligonal ali pra deixar mais clean ainda. (Vide esse site novo que estamos fazendo http://10.0.100.222)

**Comment by brunotrassante** [comment]
Acho que seria legal também colocarmos a fotinho do cara que fez o post já no "resumo" do post. Pra deixar ainda mais forte o espirito highprofile. O que acham?
