### ISSUE TITLE
Suporte para o IE?

### ISSUE THREAD

**Issue by alexandrepalagem** [CWISoftware/drops#51]
Estava pensando em tirar nosso amigo Internet Explorer da festinha...

Sem ele podemos passar a utilizar novas features sem se preocupar com ajustes específicos para tapar buracos de uma versão mais antiga do IE.

Até o IE11 tem seus problemas com flexbox :(

**Comment by brunotrassante** [comment]
Nao precisa nem ter duvida, até a MS já abandonou o IE 😛

**Comment by alexandrepalagem** [comment]
Fechou todas!
