### ISSUE TITLE
Onde fica melhor colocarmos conteúdos referentes ao post como imagens e arquivos?

### ISSUE THREAD

**Issue by Alexandre-Machado** [CWISoftware/drops#7]

**Comment by Alexandre-Machado** [comment]
Já sugiro que criemos uma pasta por arquivo de post para anexos.

**Comment by brunotrassante** [comment]
Perfeito!

**Comment by rafaeleyng** [comment]
:+1:

**Comment by Alexandre-Machado** [comment]
Não pude criar uma pasta com o nome do post junto com o arquivo .markdown em função do funcionamento do Jekyll.
Então criei uma pasta **content** na raiz e movi a pasta criada para lá.
